const resources_ja = {
  "applicationType": "アプリケーション種別",
  "clientId": "クライアント ID",
  "clientName": "クライアント名",
  "clientNames": "クライアント名 (言語別)",
  "clientSecret": "クライアントシークレット",
  "clientType": "クライアント種別",
  "clientUri": "ホームページ URL",
  "clientUris": "ホームページ URL (言語別)",
  "contacts": "連絡先",
  "defaultAcrs": "デフォルト認証コンテキスト",
  "defaultMaxAge": "最大認証有効期間",
  "deleteButtonLabel": "削除",
  "description": "クライアントの説明",
  "descriptions": "クライアントの説明 (言語別)",
  "grantTypes": "認可種別",
  "idTokenEncryptionAlg": "ID Token キー暗号化アルゴリズム",
  "idTokenEncryptionEnc": "ID Token 本文暗号化アルゴリズム",
  "idTokenSignAlg": "ID Token 署名アルゴリズム",
  "jwks": "JSON Web Key Set",
  "jwksUri": "JSON Web Key Set URL",
  "loginUri": "ログイン URL",
  "logoUri": "ロゴ URL",
  "policyUri": "ポリシー URL",
  "redirectUris": "リダイレクト URL",
  "requestUris": "リクエスト URL",
  "requestEncryptionAlg": "リクエストオブジェクトキー暗号化アルゴリズム",
  "requestEncryptionEnc": "リクエストオブジェクト本文暗号化アルゴリズム",
  "requestSignAlg": "リクエストオブジェクト署名アルゴリズム",
  "responseTypes": "応答種別",
  "sectorIdentifierUri": "セクター識別情報 URL",
  "subjectType": "サブジェクトタイプ",
  "tokenEndpoint": "トークンエンドポイント",
  "tokenAuthMethod": "トークンエンドポイントにおけるクライアント認証方式",
  "tokenAuthSignAlg": "トークンエンドポイントに渡すアサーションの署名アルゴリズム",
  "clientAuthMethod": "クライアント認証方式",
  "tosUri": "利用規約 URL",
  "tosUris": "利用規約 URL (言語別)",
  "updateButtonLabel": "設定変更",
  "userInfoEndpoint": "User Info エンドポイント",
  "userInfoEncryptionAlg": "User Info キー暗号化アルゴリズム",
  "userInfoEncryptionEnc": "User Info 本文暗号化アルゴリズム",
  "userInfoSignAlg": "User Info 署名アルゴリズム"
};