const resources_en = {
  "applicationType": "Application Type",
  "clientId": "Client ID",
  "clientName": "Client Name",
  "clientNames": "Client Names",
  "clientSecret": "Client Secret",
  "clientType": "Client Type",
  "clientUri": "Home Page URL",
  "clientUris": "Home Page URL (Language Specific)",
  "contacts": "Contacts",
  "defaultAcrs": "Default Acrs",
  "defaultMaxAge": "Default Max Age",
  "deleteButtonLabel": "Delete This App",
  "description": "Description",
  "descriptions": "Description (Language Specific)",
  "grantTypes": "Grant Types",
  "idTokenEncryptionAlg": "ID Token Encryption Algorithm (alg)",
  "idTokenEncryptionEnc": "ID Token Encryption Algorithm (enc)",
  "idTokenSignAlg": "ID Token Sign Algorithm",
  "jwks": "JSON Web Key Set",
  "jwksUri": "JSON Web Key Set URL",
  "loginUri": "Login URL",
  "logoUri": "Logo URL",
  "logoUris": "Logo URL (Language Specific)",
  "policyUri": "Policy Page URL",
  "policyUris": "Policy Page URL (Language Specific)",
  "redirectUris": "Redirect URLs",
  "requestUris": "Request URLs",
  "requestEncryptionAlg": "Request Object Encryption Algorithm (alg)",
  "requestEncryptionEnc": "Request Object Encryption Algorithm (enc)",
  "requestSignAlg": "Request Object Sign Algorithm",
  "responseTypes": "Response Types",
  "sectorIdentifierUri": "Sector Identifier",
  "subjectType": "Subject Type",
  "tokenAuthMethod": "Token Auth Method",
  "tokenAuthSignAlg": "Token Auth Sign Algorithm",
  "clientAuthMethod": "Client Auth Method",
  "tosUri": "Terms Of Service Page URL",
  "tosUris": "Terms Of Service Page URL (Language Specific)",
  "updateButtonLabel": "Update This App",
  "userInfoEncryptionAlg": "User Info Encryption Algorithm (alg)",
  "userInfoEncryptionEnc": "User Info Encryption Algorithm (enc)",
  "userInfoSignAlg": "User Info Sign Algorithm"
};